
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/missyou?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    #开启懒加载，不配置默认为开启
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write_dates_as_timestamps: true



